package wasm-link:runtime@0.4.0;

interface errors {
	variant dispatch-error {
		invalid-interface-path(string),
		invalid-function(string),
		missing-response,
		runtime-exception(string),
		invalid-argument-list,
		unsupported-type(string),
		resource-table-full,
		resource-handle-conversion-failed,
		invalid-resource-handle,
	}
}
